name: Feature Request
description: Suggest an improvement or new capability
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an improvement!
        Please check existing issues first to avoid duplicates.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the limitation or friction you're experiencing.
      placeholder: "There's no way to preview the GIF before downloading it."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like to see added or changed?
      placeholder: "Add a 'Preview' button that shows a looping preview of the GIF before exporting."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you thought about?

  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Blocking me from using the tool
    validations:
      required: true
